#!/usr/bin/env python
# -*- coding: utf-8 -*-

import click
from atlas.templating import Template

@click.command()
@click.option('--template', type=click.Path(exists=True),
              help='Template path.', required=True)
def render(template):
    source = open(template, 'r')

    template = Template(source.read())

    print(template.render())

if __name__ == '__main__':
    render()
